import os

# All paths are absolute, anchored to the project root (this file's directory).
# This allows stage scripts to be invoked from any working directory.
ROOT = os.path.dirname(os.path.abspath(__file__))

def _p(*parts):
    return os.path.join(ROOT, *parts)

DIR_EMBEDDERS = _p('embedders')
DIR_MODELS = _p('models')
# Legacy project-wide translation tables. Translations are per-set now (built by
# the set's own build.R into <set>/translations/); this stays as the fallback for
# sets whose build.R has not been updated yet. See path_translation().
DIR_TRANSLATIONS = _p('translations')

TRAIN_DIR_AUDIO = _p('audio')

# sets
SET_DIR = _p('02_set', 'sets')
SET_SUBDIR_AUDIO = 'audio'
SET_SUBDIR_EMBEDDINGS = 'embeddings'
SET_SUBDIR_RAW = 'raw'
SET_SUBDIR_TRANSLATIONS = 'translations'


def dir_set(setname):
    return os.path.join(SET_DIR, setname)

def dir_audio(setname):
    return os.path.join(SET_DIR, setname, SET_SUBDIR_AUDIO)

def dir_embeddings_raw(setname, embeddername):
    return os.path.join(SET_DIR, setname, SET_SUBDIR_EMBEDDINGS, embeddername, SET_SUBDIR_RAW)

def dir_embeddings_fold(setname, embeddername, fold):
    return os.path.join(SET_DIR, setname, SET_SUBDIR_EMBEDDINGS, embeddername, SET_SUBDIR_RAW, fold)

def dir_embeddings_augment(setname, embeddername, aug_dirname):
    return os.path.join(SET_DIR, setname, SET_SUBDIR_EMBEDDINGS, embeddername, aug_dirname)

def dir_translations(setname):
    return os.path.join(SET_DIR, setname, SET_SUBDIR_TRANSLATIONS)

def path_translation(setname, name):
    """Resolve a translation name to a CSV path for a given set.

    A set's own translations/ wins: the tables are generated by the set's
    build.R from exactly the labels that set's annotations carry, so they are
    the ones that can be complete. Sets whose build.R still predates the move
    have no such directory, and fall back to the project-wide translations/.
    """
    path_set = os.path.join(dir_translations(setname), name + '.csv')
    if os.path.exists(path_set):
        return path_set

    path_legacy = os.path.join(DIR_TRANSLATIONS, name + '.csv')
    if os.path.exists(path_legacy):
        return path_legacy

    raise FileNotFoundError(
        f'no translation {name!r} for set {setname!r}: looked in '
        f'{path_set} and {path_legacy}. Add the table to the set\'s build.R '
        f'and rerun it.'
    )


# embedding memory management. Frames per embedder forward pass — a pure
# batching knob, output-invariant. Lower it (via the env var) on GPUs with
# little VRAM; the default suits unified-memory / large-VRAM machines.
CHUNK_FRAMES = int(os.environ.get('BUZZDETECT_CHUNK_FRAMES', '300'))

# snip extraction
SNIP_BUFFER_S = 30.0

def dir_snips(setname):
    return os.path.join(SET_DIR, setname, SET_SUBDIR_AUDIO, 'snips')



