"""Export a trained model into buzzdetect's engine/models/.

    conda run -n buzzdetect-train python tools/export_onnx.py yamnet_medium_general

Reads models/<name>/ here and writes <dest>/<name>/ over in buzzdetect,
carrying both halves of the model: model.onnx for onnxruntime and model.keras
for TensorFlow, plus a model.py subclassing DualRuntimeModel, which runs
whichever of the two that environment can. One directory, either runtime --
the frozen sidecar has no TensorFlow, a checkout usually does.

The name is deliberately unchanged. Both halves are the same model: the ONNX
head matches Keras to <1e-4 and the ONNX YAMNet trunk matches the TensorFlow
one to ~1e-5 (asserted by that embedder's BUILD.py), both re-checked here on
every export. Renaming would make it look like a second model.

Only the classifier head is converted. The YAMNet trunk is not duplicated per
model -- it lives once, in buzzdetect's engine/embedders/yamnet_onnx/.
"""

# IMPORTANT: `import tensorflow` must come first, before anything that pulls in
# pandas. Keras/TF and pandas both link a copy of the same native libraries, and
# whichever loads second can bind against the first one's symbols; importing TF
# first is the ordering that works. See any 02_/03_ entry point for the full
# explanation.
import tensorflow  # noqa: F401  (import-order guard, see above)

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import config as cfg  # noqa: E402

DEST_DEFAULT = '/Users/luke/Documents/bioacoustics/buzzdetect/engine/models'

# Five minutes of field audio from Lily - Fit+Fast/2023_R3_Marysville/53. Real
# audio matters here: the head check below runs on gaussian noise, which proves
# the graph exported correctly but says nothing about behaviour on the
# post-ReLU, sparse, non-negative embeddings the model actually sees.
FIXTURE_AUDIO = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                             'fixtures', '230808_1208_s89520.flac')

# Loose enough for float32 reassociation between two runtimes, tight enough to
# catch a mis-exported graph. Same budget the engine's own tooling uses, and
# it covers both checks: the head alone lands around 7e-6, and the end-to-end
# check -- which composes the ONNX trunk's own ~1e-5 drift through the head --
# lands around 4e-5 on the fixture.
TOL = 1e-4

# Which ONNX embedder in buzzdetect stands in for each embedder here. An
# embedder missing from this table has no ONNX build over there yet; adding a
# row without building one just produces a model the engine can't load.
EMBEDDERS_ONNX = {
    'yamnet': 'yamnet_onnx',
}

# Only what the engine reads: classes names the result columns and
# digits_results sets their rounding. The embedder is not among them -- the
# generated model.py names one per runtime, because which embedder applies
# depends on which runtime ends up running. Training metadata is deliberately
# not shipped yet.
KEYS_CONFIG = ('classes', 'digits_results')

TEMPLATE_MODEL_PY = '''from src.inference.models import DualRuntimeModel


class {classname}(DualRuntimeModel):
    """Generated by buzzdetect-training tools/export_onnx.py. Do not edit.

    Holds both halves: model.onnx for onnxruntime and model.keras for
    TensorFlow, checked against each other at export time. DualRuntimeModel
    runs whichever this environment can.
    """

    modelname = "{modelname}"
    embeddername_onnx = '{embeddername_onnx}'
    embeddername_tensorflow = '{embeddername_tensorflow}'
    digits_results = {digits_results}
'''


# Run by the engine's own interpreter, because neither environment
# has both halves: TensorFlow lives here, onnxruntime plus the ONNX YAMNet trunk
# live there. Takes decoded samples rather than an audio path so that any
# difference in how the two repos load and resample audio stays out of the
# comparison -- what's being measured is the model, not the decoder.
DRIVER_VERIFY = '''
import os, sys
import numpy as np

sys.path.insert(0, os.getcwd())
from src import config as cfg
cfg.DIR_MODELS = sys.argv[1]
import src.inference.models as models
models.cfg = cfg

model = models.load_model(sys.argv[2], framehop_prop=1, initialize=True)
np.save(sys.argv[4], np.asarray(model.predict(np.load(sys.argv[3]))))
'''


def engine_python_for(dir_dest):
    """The engine's interpreter, inferred from the destination.

    dir_dest is <repo>/engine/models, so the engine is its parent.
    """
    return os.path.join(os.path.dirname(os.path.abspath(dir_dest)),
                        '.venv', 'bin', 'python3')


def verify_audio(modelname, dir_stage, path_audio, python_engine, dir_engine):
    """Compare scores from real audio, TensorFlow here against ONNX there.

    Stronger than the head check: this runs the whole path, so it sees the ONNX
    YAMNet trunk's drift composed through the head, which is what actually
    decides whether an analysis moves. Only valid at framehop_prop=1 -- the ONNX
    embedder refuses anything else.
    """
    import keras
    import librosa

    from embedders.embedding import load_embedder



    print(f'verifying end-to-end on {os.path.basename(path_audio)}')
    embedder = load_embedder('yamnet', framehop_prop=1, initialize=True)
    samples, _ = librosa.load(path_audio, sr=embedder.samplerate, mono=True)
    samples = samples.astype(np.float32)

    model = keras.saving.load_model(
        os.path.join(cfg.DIR_MODELS, modelname, 'model.keras'), compile=False)
    scores_tf = np.asarray(model(np.asarray(embedder.embed(samples))))

    with tempfile.TemporaryDirectory() as dir_tmp:
        path_samples = os.path.join(dir_tmp, 'samples.npy')
        path_scores = os.path.join(dir_tmp, 'scores.npy')
        np.save(path_samples, samples)
        # Pin the runtime. The staged directory holds both halves now, so an
        # engine venv that happens to have TensorFlow would otherwise pick it
        # and the check would compare TensorFlow against itself.
        env = dict(os.environ, BUZZDETECT_RUNTIME='onnx')
        subprocess.run(
            [python_engine, '-c', DRIVER_VERIFY, os.path.dirname(dir_stage),
             modelname, path_samples, path_scores],
            cwd=dir_engine, check=True, env=env)
        scores_onnx = np.load(path_scores)

    if scores_tf.shape != scores_onnx.shape:
        raise SystemExit(f'frame/class mismatch: tensorflow {scores_tf.shape} vs '
                         f'onnx {scores_onnx.shape}')

    d = float(np.abs(scores_tf - scores_onnx).max())
    agree = float((scores_tf.argmax(1) == scores_onnx.argmax(1)).mean())
    print(f'  {scores_tf.shape[0]} frames, max|d|={d:.2e}, top-class agreement={agree:.4f}')
    if d > TOL:
        raise SystemExit(f'end-to-end parity FAILED: {d:.2e} > {TOL}')
    return d


def classname_for(modelname):
    return ''.join(part[:1].upper() + part[1:] for part in modelname.split('_'))


def export(modelname, dir_dest, embeddername=None, force=False,
           path_audio=None, python_engine=None):
    """Build the export in a staging dir, check it, and only then move it into place.

    Staging is what makes a failed check harmless: nothing lands in the
    destination -- and no existing export there is disturbed -- unless both
    parity checks pass.
    """
    import keras
    import onnxruntime as ort

    dir_src = os.path.join(cfg.DIR_MODELS, modelname)
    if not os.path.isdir(dir_src):
        raise SystemExit(f'no such model: {dir_src}')

    with open(os.path.join(dir_src, 'config_model.json')) as f:
        config = json.load(f)

    embeddername_tf = config['embeddername']
    if embeddername is None:
        embeddername = EMBEDDERS_ONNX.get(embeddername_tf)
        if embeddername is None:
            raise SystemExit(
                f"no ONNX embedder known for '{config['embeddername']}'. Build one in "
                f'buzzdetect and add it to EMBEDDERS_ONNX, or pass --embeddername.')

    dir_out = os.path.join(dir_dest, modelname)
    if os.path.exists(dir_out) and not force:
        raise SystemExit(f'{dir_out} already exists; pass --force to overwrite')

    dir_staging = tempfile.mkdtemp(prefix='export_onnx_')
    dir_stage = os.path.join(dir_staging, modelname)
    os.makedirs(dir_stage)

    print(f'loading {dir_src}/model.keras')
    model = keras.saving.load_model(os.path.join(dir_src, 'model.keras'), compile=False)
    n_embeddings = model.inputs[0].shape[-1]
    # Keras refuses to export a model it has never seen called.
    model(np.zeros((1, n_embeddings), dtype=np.float32))

    path_onnx = os.path.join(dir_stage, 'model.onnx')
    print(f'exporting {path_onnx}')
    model.export(path_onnx, format='onnx', verbose=False)

    session = ort.InferenceSession(path_onnx, providers=['CPUExecutionProvider'])
    name_in = session.get_inputs()[0].name
    print(f'  {os.path.getsize(path_onnx) / 1e6:.2f} MB, '
          f'in {session.get_inputs()[0].shape} out {session.get_outputs()[0].shape}')

    print('checking parity against the keras model')
    rng = np.random.default_rng(0)
    worst = 0.0
    for n_frames in (1, 8, 512):
        embeddings = rng.standard_normal((n_frames, n_embeddings)).astype(np.float32)
        expected = np.asarray(model(embeddings))
        got = session.run(None, {name_in: embeddings})[0]
        if expected.shape != got.shape:
            raise SystemExit(f'shape mismatch: keras {expected.shape} vs onnx {got.shape}')
        d = float(np.abs(expected - got).max())
        worst = max(worst, d)
        print(f'  n_frames={n_frames:<5} max|d|={d:.2e}')
    if worst > TOL:
        raise SystemExit(f'head parity FAILED: {worst:.2e} > {TOL}; nothing shipped')
    print(f'head parity OK: {worst:.2e}')

    # The TensorFlow half, shipped beside the ONNX one so a checkout with
    # TensorFlow can run the model the way it was trained.
    shutil.copy2(os.path.join(dir_src, 'model.keras'),
                 os.path.join(dir_stage, 'model.keras'))

    config_out = {k: config[k] for k in KEYS_CONFIG}
    with open(os.path.join(dir_stage, 'config_model.json'), 'w') as f:
        json.dump(config_out, f, indent=2)

    with open(os.path.join(dir_stage, 'model.py'), 'w') as f:
        f.write(TEMPLATE_MODEL_PY.format(
            classname=classname_for(modelname),
            modelname=modelname,
            embeddername_onnx=embeddername,
            embeddername_tensorflow=embeddername_tf,
            digits_results=config_out['digits_results'],
        ))

    # Needs the finished staging dir -- the engine loads the model by name out
    # of it, model.py and config_model.json included.
    if path_audio is not None:
        verify_audio(modelname, dir_stage, path_audio, python_engine,
                     os.path.dirname(os.path.abspath(dir_dest)))

    # Loading model.py leaves bytecode behind; it must not ship.
    shutil.rmtree(os.path.join(dir_stage, '__pycache__'), ignore_errors=True)

    if os.path.exists(dir_out):
        shutil.rmtree(dir_out)
    shutil.move(dir_stage, dir_out)
    shutil.rmtree(dir_staging, ignore_errors=True)
    print(f'wrote {dir_out}')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('modelname', help='model directory name under models/')
    parser.add_argument('--dest', default=DEST_DEFAULT,
                        help=f'engine model directory (default: {DEST_DEFAULT})')
    parser.add_argument('--embeddername', default=None,
                        help='override the ONNX embedder chosen from EMBEDDERS_ONNX')
    parser.add_argument('--force', action='store_true',
                        help='overwrite an existing export')
    parser.add_argument('--verify-audio', default=FIXTURE_AUDIO, metavar='PATH',
                        help='audio to run the end-to-end check on '
                             '(default: the bundled fixture)')
    parser.add_argument('--no-verify-audio', dest='verify_audio',
                        action='store_const', const=None,
                        help="skip the end-to-end check, leaving only the head "
                             "check; use when the engine's venv isn't available")
    parser.add_argument('--engine-python', default=None, metavar='PATH',
                        help='engine interpreter '
                             '(default: <dest>/../.venv/bin/python3)')
    args = parser.parse_args()

    if not os.path.isdir(args.dest):
        raise SystemExit(f'destination does not exist: {args.dest}')
    python_engine = args.engine_python or engine_python_for(args.dest)
    if args.verify_audio is not None:
        # Both checked up front: the export is a slow way to discover a typo.
        if not os.path.isfile(args.verify_audio):
            raise SystemExit(f'no such audio: {args.verify_audio}')
        if not os.path.isfile(python_engine):
            raise SystemExit(f'no engine interpreter at {python_engine}; pass '
                             f'--engine-python or --no-verify-audio')

    export(args.modelname, args.dest, args.embeddername, args.force,
           args.verify_audio, python_engine)


if __name__ == '__main__':
    main()
